services:
  database:
    image: postgres:16-alpine
    restart: "on-failure"
    ports:
      - "7082:5432"
    volumes:
      - database:/data/postgres
    environment:
      - PGDATA=/data/postgres
      - POSTGRES_DB=star_wars
      - POSTGRES_USER=star_wars_user
      - POSTGRES_PASSWORD=star_wars_password

  back:
    build:
      context: ./back
    ports:
      - "4000:4000"
    restart: "on-failure"
    volumes:
      - ./back:/app
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://star_wars_user:star_wars_password@database:5432/star_wars
      - API_ENTRYPOINT=https://swapi.dev/api
      - JWT_SECRET=MyBestSecret

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: "on-failure"
    tty: true
    stdin_open: true
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    environment:
      - REACT_APP_API_ENTRYPOINT=http://localhost:4000
    command: npm run dev -- --host
    depends_on:
      - back

volumes:
  database:
