---
# --- Backend Deployment (Python API) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  namespace: starwars
spec:
  replicas: 3 # Number of replicas for high availability
  selector:
    matchLabels:
      component: back
  template:
    metadata:
      labels:
        component: back
    spec:
      containers:
        - name: server
          # Docker image optimized for production
          image: jedy-starwarskubernetes-back:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          # Loading all configuration (ConfigMaps and Secrets) via envFrom
          envFrom:
            - configMapRef:
                name: back-configmap
            - secretRef:
                name: pgpassword
            # - secretRef:
            #     name: google-api-key # Uncomment if using Google API
            # - secretRef:
            #     name: openrouter-api-key # Uncomment if using OpenRouter API
            - secretRef:
                name: jwt-secret
--- 
# --- Internal Service for Backend ---
apiVersion: v1
kind: Service
metadata:
  name: back-cluster-ip-service
  namespace: starwars
spec:
  type: ClusterIP # Accessible only inside the cluster
  selector:
    component: back
  ports:
    - port: 4000 # Port exposed by the Service
      targetPort: 4000 # Target container port
