---
# --- Frontend Deployment (Astro SSR) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: starwars
spec:
  replicas: 3 # High Availability
  selector:
    matchLabels:
      component: front
  template:
    metadata:
      labels:
        component: front
    spec:
      containers:
        - name: client
          # Docker image optimized for production
          image: jedy-starwarskubernetes-front:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4321
          resources: # Resource definition to avoid "noisy neighbor" issues
            requests:
              cpu: "100m" # Request for 0.1 CPU
              memory: "128Mi" # Request for 128 MB of memory
            limits:
              cpu: "200m" # Limit to 0.2 CPU
              memory: "256Mi" # Limit to 256 MB of memory
          # Loading global environment variables from ConfigMap
          envFrom:
            - configMapRef:
                name: jedy-config
---
# --- Internal Service for Frontend ---
apiVersion: v1
kind: Service
metadata:
  name: front-cluster-ip-service
  namespace: starwars
spec:
  type: ClusterIP # Accessible only inside the cluster
  selector:
    component: front
  ports:
    - port: 4321
      targetPort: 4321